### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by jnguyen32** [pawprintdigital/laravel-queue-raw-sqs#1]
Could you provide an example of how to consume the message?

I can see it instantiating the correct Job Handler class, but I don't see any message body being passed through the handler

**Comment by leemathewbrooks** [comment]
> Could you provide an example of how to consume the message?
> 
> I can see it instantiating the correct Job Handler class, but I don't see any message body being passed through the handler

Hello there, 

Apologies for the delayed response.
Given the configuration below, you can consume it in the following way:

```
    'ppevents' => [
      'driver' => 'rawsqs',
      'key' => env('AWS_ACCESS_KEY_ID'),
      'secret' => env('AWS_SECRET_ACCESS_KEY'),
      'prefix' => 'https://sqs.eu-west-1.amazonaws.com/XXXX',
      'queue' => 'Pawprint-Events',
      'region' => env('AWS_REGION'),
      'routes' => [
        '*' =>'App\\Jobs\\Emarketing\\ProcessEvent'
      ]
    ],
```

The entire of content of the raw message can is then passed to your Job class, e.g

```
  public $data;

  public function __construct($data)
  {
    $this->data = $data;
  }

  public function handle()
  {
    $payload = $this->data;

```

`$payload` would then contain your message. 
I'll update the readme to make this clearer!

Lee
